class SlotManager:

    def extract_title(self, text): ...
    def extract_date(self, text): ...
    def extract_category(self, text): ...

    def resolve_task_reference(self, text, tasks): ...
    def resolve_delete_reference(self, text, tasks): ...