training_examples = [

    # View Tasks
    ("show my tasks", "view_tasks"),
    ("list tasks", "view_tasks"),
    ("display tasks", "view_tasks"),
    ("what tasks do i have", "view_tasks"),
    ("show task list", "view_tasks"),
    ("show all tasks", "view_tasks"),
    ("what tasks do i have", "view_tasks"),
    ("display my tasks", "view_tasks"),
    ("show pending tasks", "view_tasks"),
    ("open task list", "view_tasks"),
    ("view task list", "view_tasks"),
    ("show all my tasks", "view_tasks"),
    ("what are my tasks", "view_tasks"),
    ("open tasks", "view_tasks"),
    ("task list please", "view_tasks"),
    ("display all tasks", "view_tasks"),
    ("show pending tasks", "view_tasks"),
    ("list all my work", "view_tasks"),
    ("do i have tasks", "view_tasks"),
    ("what is on my list", "view_tasks"),
    ("check my task list", "view_tasks"),

    # Today's priorities
    ("what should i do today", "today"),
    ("recommend tasks", "today"),
    ("what is important today", "today"),
    ("show priorities", "today"),
    ("what should i focus on", "today"),
    ("what should i do today", "today"),
    ("what do i focus on", "today"),
    ("show today's priorities", "today"),
    ("what is important now", "today"),
    ("help me plan my day", "today"),
    ("top tasks for today", "today"),
    ("what should i start with", "today"),
    ("urgent tasks today", "today"),
    ("plan my tasks", "today"),
    ("what needs attention", "today"),

    # Productivity
    ("show productivity", "productivity"),
    ("productivity score", "productivity"),
    ("how productive am i", "productivity"),
    ("analyze productivity", "productivity"),
    ("how productive have i been lately", "productivity"),
    ("am i productive", "productivity"),
    ("check my productivity", "productivity"),
    ("show productivity report", "productivity"),
    ("how am i performing", "productivity"),
    ("give me my productivity stats", "productivity"),
    ("productivity analysis", "productivity"),
    ("how productive am i today", "productivity"),
    ("productivity report", "productivity"),
    ("show my performance", "productivity"),
    ("am i doing well", "productivity"),
    ("check my efficiency", "productivity"),
    ("how is my productivity", "productivity"),
    ("give productivity stats", "productivity"),
    ("analyze my work rate", "productivity"),
    ("am i improving", "productivity"),
    ("productivity overview", "productivity"),

    # Habits
    ("show habits", "habits"),
    ("analyze habits", "habits"),
    ("habit report", "habits"),
    ("my behavior patterns", "habits"),
    ("what are my habits", "habits"),
    ("analyze my behavior", "habits"),
    ("show habit report", "habits"),
    ("how do i behave with tasks", "habits"),
    ("pattern analysis", "habits"),
    ("my task habits", "habits"),
    ("behavior insights", "habits"),
    ("what patterns do i show", "habits"),
    ("am i consistent", "habits"),
    ("habit tracking", "habits"),

    # Memory
    ("show memory", "memory"),
    ("ai memory", "memory"),
    ("memory insights", "memory"),
    ("what do you remember", "memory"),
    ("show my memory", "memory"),
    ("ai memory report", "memory"),
    ("user profile", "memory"),
    ("what have you learned about me", "memory"),
    ("my stats", "memory"),
    ("personal insights", "memory"),
    ("stored information", "memory"),
    ("my usage data", "memory"),
    ("memory summary", "memory"),

    # Complete Task
    ("complete task", "complete_task"),
    ("mark task complete", "complete_task"),
    ("finish task", "complete_task"),
    ("finish this task", "complete_task"),
    ("mark as done", "complete_task"),
    ("task completed", "complete_task"),
    ("i finished a task", "complete_task"),
    ("close task", "complete_task"),
    ("done with task", "complete_task"),
    ("complete this", "complete_task"),
    ("mark finished", "complete_task"),
    ("task is done", "complete_task"),
    ("i am done", "complete_task"),

    # Predictive
    ("show predictions", "predict"),
    ("predict task completion", "predict"),
    ("predictive insights", "predict"),
    ("predict my tasks", "predict"),
    ("will i complete this", "predict"),
    ("completion prediction", "predict"),
    ("task success chance", "predict"),
    ("what will i finish", "predict"),
    ("predict performance", "predict"),
    ("likelihood of completion", "predict"),
    ("future task outcome", "predict"),
    ("how likely am i to finish", "predict"),
    ("forecast my tasks", "predict"),

    # Briefing
    ("daily briefing", "brief"),
    ("generate briefing", "brief"),
    ("show briefing", "brief"),
    ("give me daily briefing", "brief"),
    ("summarize my day", "brief"),
    ("daily summary", "brief"),
    ("what happened today", "brief"),
    ("task report", "brief"),
    ("overview of my tasks", "brief"),
    ("summary report", "brief"),
    ("brief me", "brief"),
    ("what should i know", "brief"),
    ("daily AI report", "brief"),
]